version: '3'

services:
  frontend:
    container_name: frontend
    build: ./sedaro-nano
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./sedaro-nano/app/node_modules/:/app/node_modules/
    command: npm start
  backend-api:
    container_name: backend-api
    build: ./backend
    ports:
      - '5000:5000'
